export const SET_POST_ACTIVE = "SET_POST_ACTIVE";

export const SET_LIKE_COUNTER = "SET_LIKE_COUNTER";

export const SEND_UPDATE_LIKE_COUNTER_REQUEST = "SEND_UPDATE_LIKE_COUNTER_REQUEST";

export const UPDATE_LIKE_COUNTER_SUCCESS = "UPDATE_LIKE_COUNTER_SUCCESS";

export const SET_IS_POST_FAVORITE = "SET_IS_POST_FAVORITE";