export const SET_POST_ACTIVE = "SET_POST_ACTIVE";

export const SET_LIKE_COUNTER = "SET_LIKE_COUNTER";

export const UPDATE_LIKE_COUNTER_REQUEST = "LOAD_UPDATE_LIKE_COUNTER_REQUEST";

export const UPDATE_LIKE_COUNTER_REQUEST_SUCCESS = "LOAD_UPDATE_LIKE_COUNTER_REQUEST_SUCCESS";