export const OPEN_MODAL = "OPEN_MODAL"
export const CLOSE_MODAL = "CLOSE_MODAL"
export const ACTIVE_USER_TITLE = "ACTIVE_USER_TITLE"
export const SET_URL = "SET_URL"
export const SET_POST_ID = "SET_POST_ID"