export const LOAD_COMMENTS_REQUEST = "LOAD_COMMENTS_REQUEST";

export const LOAD_COMMENTS_SUCCESS = "LOAD_COMMENTS_SUCCESS";

export const SET_COMMENTS = "SET_COMMENTS";

export const LOAD_COMMENTS_FAILURE = "LOAD_COMMENTS_FAILURE";